### PR TITLE
made dry run an available flag

### PR DESCRIPTION
**Pull request by mtintes**
This should add the dry run as a pass through to the helm client I think.

TBH I was not sure how to test this locally as I am pretty new to golang and haven't quite figured it totally out yet. Happy to take some feedback.

### CODE REVIEW

**Review by martin-helmich — APPROVED** [review]

**Comment by martin-helmich** [comment]
I'm unsure how much testing effort is actually required here, as basically all these functions do is call the appropriate functions from the `helm.sh/helm/v3/pkg/action` package. The only tests that I could imagine would either assert that the dry-run flag is correctly passed into the `action.Install`/`action.Upgrade` structs (which would be trivial) or assert that a dry-run actually does a dry run (which would most certainly _not_ be trivial, but would essentially amount to testing Helm itself, which also sounds unnecessary).

I'd be fine with merging this as-is. What do you think, @hensur @elenz97?

**Comment by elenz97** [comment]
@martin-helmich I'm fine with merging, too.
I think testing functionality of Helm's command-line flags _themselves_ should never be in scope of this project. As a user, I'd assume that any flag value I give `go-helm-client` will be passed to Helm.

So far we've never tested whether values are passed correctly into `action.Install` / `action.Upgrade` or not.
As there is no complex mapping happening anyway, I don't see a crucial reason why we should test this.

**Review by elenz97 — APPROVED** [review]

**Comment by martin-helmich** [comment]
Let's go ahead, then. Thanks for your contribution, @mtintes! 👍

**Comment by mtintes** [comment]
@martin-helmich @elenz97 sorry to bother you, are you on a specific cadence for doing releases? It would be nice to use the dry run functionality in my project soon if possible. Thanks for your time.

**Pull request merged**
