### PR TITLE
Pass debug log to HelmClient

### PR DESCRIPTION
**Pull request by meatballhat**
This is something of a follow-up to #20 as I noticed the remaining logging that wasn't coming from the `action.DebugLog` func I'd passed in. I'm not happy about squashing together the warning-level and error-level logs, but I didn't want to introduce yet another logger 😕. The extension of the `Client` interface also isn't strictly necessary if using the same `action.DebugLog` func accepted via `*Options` is acceptable. Feedback very much appreciated!

### CODE REVIEW

**Review by dgloeckner — APPROVED** [review]

**Comment by dgloeckner** [comment]
@meatballhat  thanks for looking into this. I can help to sort out the conflicts if you like :)

**Comment by martin-helmich** [comment]
Sorry for letting this one stew for so long. Seems I've just introduced another merge conflict by merging #38 and hope I've resolved them correctly. Will merge shortly as soon as the tests pass.

**Comment by martin-helmich** [comment]
> Will merge shortly as soon as the tests pass.

Yeaaah... That didn't work out particularly well for me... 😕

**Review by martin-helmich — APPROVED** [review]

**Comment by meatballhat** [comment]
Thank you @martin-helmich! 🎉

**Pull request merged**
