### PR TITLE
move getChart  to public

### PR DESCRIPTION
**Pull request by izturn**
chart  "bitnami/contour"  have some CRDs under the  directory "resources",  not "crds", so download the chart first  and  manage the CRDs by manual is likely the prefer choice,  move the "getChart" to public, make my life easy, perhaps someone else like the idea too.

Signed-off-by: Gang Liu <gang.liu@daocloud.io>

### CODE REVIEW

**Comment by zvonkok** [comment]
I need this as well, need to preproces some metadata. Will take a look at this PR as well. I have also a PR that does something similar. Will abandon my in favour of this.

**Review by elenz97 — CHANGES_REQUESTED** [review]
Thanks again @izturn and +1 for this. Can you rebase your PR on the current `mittwald:master`?

**Comment by izturn** [comment]
done

**Review by elenz97 — APPROVED** [review]

**Comment by ottramst** [comment]
Hey @zvonkok @izturn @elenz97 !

Have a requirement for modifying the chart values, but I can't seem to figure out how an OCI chart can be pulled through this function. I constantly get an error `missing registry client`, even though the `GetChart` function is called through the same initialized client that can install OCI charts.

Do you guys have any examples of calling this function so that it works for OCI charts?

Thanks!

**Pull request merged**
