### PR TITLE
upgrade to k8s v0.29.x

### LINKED ISSUE #193: Kubernetes 0.29.0 update throws error
`mittwald/go-helm-client@v0.12.4/client_getter.go:61:53: not enough arguments in call to restmapper.NewShortcutExpander`

Recreate with updating k8s golang client to v0.29.0.

### PR DESCRIPTION
**Pull request by yulin-li**
fix #193

### CODE REVIEW

**Review by elenz97 — CHANGES_REQUESTED** [review]
@yulin-li Could you rebase this PR on the current master?

**Review by sebrandon1 — APPROVED** [review]

**Comment by yulin-li** [comment]
> @yulin-li Could you rebase this PR on the current master?

sure, I resolved the conflicts

**Comment by 0AdityaD** [comment]
Can we get this merged?

**Comment by 0AdityaD** [comment]
Can we get this merged? @elenz97

**Review by elenz97 — APPROVED** [review]
lgtm!

**Comment by elenz97** [comment]
@0AdityaD  The changes are now available in the latest [v0.12.6 release](https://github.com/mittwald/go-helm-client/releases/tag/v0.12.6) :+1:

**Pull request merged**
