### PR TITLE
Feature - Chart Tests

### PR DESCRIPTION
**Pull request by s4arkbyt3**
Added `RunChartTests` function which executes the tests specified on the release

### CODE REVIEW

**Review by elenz97 — APPROVED** [review]
lgtm

**Comment by elenz97** [comment]
@s4arkbyt3 Code generation actions are failing, could you run `go generate ./...` and update your PR?

**Comment by cheerioskun** [comment]
@s4arkbyt3 are you planning to update this? If not I can create an updated PR

**Comment by zvonkok** [comment]
@cheerioskun  I am also interested in this, I can review and test from my side. 
@s4arkbyt3 Any update from your side?

**Comment by elenz97** [comment]
should be superseded by: https://github.com/mittwald/go-helm-client/pull/191

**Pull request closed without merging**
